gcp:
  type: POSTGRES_12
  databaseName: spre-subsumsjon
kafkaPool: nav-dev
kafkaConsumerGroup: tbd-spre-subsumsjon-v2
kafkaResetPolicy: earliest
env:
  - name: SUBSUMSJON_TOPIC
    value: flex.omrade-helse-etterlevelse
