replicas:
  min: 2
  max: 8
kafkaPool: nav-prod
kafkaResetPolicy: earliest
env:
  - name: SUBSUMSJON_TOPIC
    value: flex.omrade-helse-etterlevelse
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.subsumsjon.v1
