kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsprearbeidsgiver
env:
- name: KAFKA_BOOTSTRAP_SERVERS
  value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
- name: ArbeidsgiverAiventopic
  value: "true"
